import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "../public/styles/stylesheet.css";
import AOSInit from "./components/common/AOSInit";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AOSInit />
        {children}
      </body>
    </html>
  );
}
